### ISSUE TITLE
?guild-info crashes

### ISSUE THREAD

**Issue by carson-000** [JokerJosh1234/EchoBot#2]
Running ?guild-info crashes the bot.

```
Unhandled Exception: System.ArgumentException: Field value length must be less than or equal to 1024.
Parameter name: Value
   at Discord.EmbedFieldBuilder.set_Value(Object value)
   at Discord.EmbedBuilder.AddField(String name, Object value, Boolean inline)
   at Bot.Commands.Text.GuildInfo.<HandleExecute>d__1.MoveNext() in C:\Users\NoobZoid\Downloads\EchoBot-main\EchoBot-main\TextCommands\GuildInfo.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

havent modified the bot yet, ill fix this soon though and make a pull request if i have time

**Comment by JokerJosh1234** [comment]
hello, this is likely due to a server data being longer than 1024 characters, such as roles, or invites. one of these datas (could be another one) are too long, you can fix this by trimming the data (.Trim(0, 1024) [i think])

**Comment by JokerJosh1234** [comment]
just looked at the line number where the error was coming from, and yes it is the roles. you likely have alot of roles that is longer than 1024 characters.

you should be able to replace that line with:

           string roles = string.Join(", ", guild.Roles.Skip(1).Select(role => role.Mention));

            if(roles.Length > 1024)
                roles = roles.Substring(0, 1021) + '...';

            // displays the guilds roles (should skip @everyone)
            embed.AddField("Roles", guild.Roles.Count > 1 ? roles : "None", true);`

let me know if it works!

**Comment by carson-000** [comment]
that fixed it, thanks!
